ALTER TABLE `Boms` MODIFY `Id` BIGINT AUTO_INCREMENT;
ALTER TABLE `Customers` MODIFY `Id` BIGINT AUTO_INCREMENT;
ALTER TABLE `DefectCodes` MODIFY `Id` BIGINT AUTO_INCREMENT;
ALTER TABLE `Equipment` MODIFY `Id` BIGINT AUTO_INCREMENT;
ALTER TABLE `InspectionStandards` MODIFY `Id` BIGINT AUTO_INCREMENT;
ALTER TABLE `Permissions` MODIFY `Id` BIGINT AUTO_INCREMENT;
ALTER TABLE `Processes` MODIFY `Id` BIGINT AUTO_INCREMENT;
ALTER TABLE `Products` MODIFY `Id` BIGINT AUTO_INCREMENT;
ALTER TABLE `Roles` MODIFY `Id` BIGINT AUTO_INCREMENT;
ALTER TABLE `Routings` MODIFY `Id` BIGINT AUTO_INCREMENT;
ALTER TABLE `Suppliers` MODIFY `Id` BIGINT AUTO_INCREMENT;
ALTER TABLE `Tools` MODIFY `Id` BIGINT AUTO_INCREMENT;
ALTER TABLE `Users` MODIFY `Id` BIGINT AUTO_INCREMENT;

ALTER TABLE `Boms` MODIFY `ProductId` BIGINT NULL, MODIFY `RoutingId` BIGINT NULL;
ALTER TABLE `Routings` MODIFY `ProcessId` BIGINT NULL, MODIFY `EquipmentId` BIGINT NULL;

ALTER TABLE `inspection_plans` MODIFY `productId` BIGINT NULL, MODIFY `materialId` BIGINT NULL, 
  MODIFY `supplierId` BIGINT NULL, MODIFY `customerId` BIGINT NULL, 
  MODIFY `processId` BIGINT NULL, MODIFY `equipmentId` BIGINT NULL,
  MODIFY `createdBy` BIGINT NULL, MODIFY `organizationId` BIGINT NULL;

ALTER TABLE `inspection_plan_items` MODIFY `inspectionStandardId` BIGINT NULL;
ALTER TABLE `inspection_items` MODIFY `standardId` BIGINT NULL;

ALTER TABLE `iqc_receipts` MODIFY `productId` BIGINT NULL, MODIFY `supplierId` BIGINT NULL, 
  MODIFY `receivedBy` BIGINT NULL;

ALTER TABLE `iqc_inspections` MODIFY `inspectorId` BIGINT NULL;

ALTER TABLE `supplier_scores` MODIFY `supplierId` BIGINT NULL, MODIFY `scoredById` BIGINT NULL;

ALTER TABLE `Products` MODIFY `org_id` BIGINT NULL COMMENT '所属组织ID';
ALTER TABLE `Processes` MODIFY `org_id` BIGINT NULL COMMENT '所属组织ID';
ALTER TABLE IF EXISTS `Equipments` MODIFY `org_id` BIGINT NULL COMMENT '所属组织ID';

SELECT 'SCHEMA_UPGRADE_COMPLETE' AS status;
