import type { MenuConfig } from '@/types/tab'

export const menuConfigs: MenuConfig[] = [
  {
    id: 'dashboard',
    name: '首页',
    icon: 'Odometer',
    path: '/dashboard',
    closable: false,
    order: 0,
    module: 'dashboard',
  },
  {
    id: 'basic-data',
    name: '基础数据',
    icon: 'Collection',
    path: '_basic',
    closable: true,
    order: 1,
    module: 'basic-data',
    children: [
      { id: 'basic-product', name: '产品管理', icon: 'Goods', path: '/basic-data/product', closable: true, order: 1, module: 'basic-data' },
      { id: 'basic-process', name: '工序管理', icon: 'Tools', path: '/basic-data/process', closable: true, order: 2, module: 'basic-data' },
      { id: 'basic-routing', name: '工艺路线', icon: 'Connection', path: '/basic-data/routing', closable: true, order: 3, module: 'basic-data' },
      { id: 'basic-bom', name: 'BOM清单', icon: 'Document', path: '/basic-data/bom', closable: true, order: 4, module: 'basic-data' },
      { id: 'basic-standard', name: '检验标准', icon: 'List', path: '/basic-data/standard', closable: true, order: 5, module: 'basic-data' },
      { id: 'basic-defect', name: '不良代码', icon: 'WarningFilled', path: '/basic-data/defect', closable: true, order: 6, module: 'basic-data' },
      { id: 'basic-equipment', name: '设备管理', icon: 'Monitor', path: '/basic-data/equipment', closable: true, order: 7, module: 'basic-data' },
      { id: 'basic-tool', name: '刀具管理', icon: 'Setting', path: '/basic-data/tool', closable: true, order: 8, module: 'basic-data' },
      { id: 'basic-supplier', name: '供应商管理', icon: 'Van', path: '/basic-data/supplier', closable: true, order: 9, module: 'basic-data' },
      { id: 'basic-customer', name: '客户管理', icon: 'User', path: '/basic-data/customer', closable: true, order: 10, module: 'basic-data' },
    ],
  },
  {
    id: 'iqc',
    name: 'IQC来料检验',
    icon: 'Goods',
    path: '_iqc',
    closable: true,
    order: 1,
    module: 'iqc',
    children: [
      { id: 'iqc-params', name: '动态参数配置', icon: 'Setting', path: '/iqc/params', closable: true, order: 1, module: 'iqc' },
      { id: 'iqc-receipts', name: '来料登记', icon: 'Box', path: '/iqc/receipts', closable: true, order: 2, module: 'iqc' },
      { id: 'iqc-inspections', name: '检验单', icon: 'Document', path: '/iqc/inspections', closable: true, order: 3, module: 'iqc' },
      { id: 'iqc-anomalies', name: '来料异常', icon: 'WarningFilled', path: '/iqc/anomalies', closable: true, order: 4, module: 'iqc' },
      { id: 'iqc-suppliers', name: '供应商评分', icon: 'DataAnalysis', path: '/iqc/suppliers', closable: true, order: 5, module: 'iqc' },
      { id: 'iqc-trace', name: '批次追溯', icon: 'Search', path: '/iqc/trace', closable: true, order: 6, module: 'iqc' },
    ],
  },
  {
    id: 'ipqc',
    name: 'IPQC过程检验',
    icon: 'Tools',
    path: '_ipqc',
    closable: true,
    order: 2,
    module: 'ipqc',
    children: [
      { id: 'ipqc-first-pieces', name: '首件检验', icon: 'DocumentChecked', path: '/ipqc/first-pieces', closable: true, order: 1, module: 'ipqc' },
      { id: 'ipqc-patrols', name: '巡检记录', icon: 'List', path: '/ipqc/patrols', closable: true, order: 2, module: 'ipqc' },
      { id: 'ipqc-plans', name: '巡检计划', icon: 'Calendar', path: '/ipqc/plans', closable: true, order: 3, module: 'ipqc' },
      { id: 'ipqc-risk', name: 'AI风险仪表盘', icon: 'DataAnalysis', path: '/ipqc/risk', closable: true, order: 4, module: 'ipqc' },
    ],
  },
  {
    id: 'fqc',
    name: 'FQC/OQC成品检验',
    icon: 'Finished',
    path: '_fqc',
    closable: true,
    order: 3,
    module: 'fqc',
    children: [
      { id: 'fqc-inspections', name: '成品检验', icon: 'DocumentChecked', path: '/fqc/inspections', closable: true, order: 1, module: 'fqc' },
      { id: 'fqc-batches', name: '批次管理', icon: 'Box', path: '/fqc/batches', closable: true, order: 2, module: 'fqc' },
      { id: 'fqc-releases', name: '出货放行', icon: 'Ship', path: '/fqc/releases', closable: true, order: 3, module: 'fqc' },
      { id: 'fqc-packaging', name: '包装确认', icon: 'TakeawayBox', path: '/fqc/packaging', closable: true, order: 4, module: 'fqc' },
    ],
  },
  {
    id: 'spc',
    name: 'SPC统计分析',
    icon: 'DataAnalysis',
    path: '/spc',
    closable: true,
    order: 4,
    module: 'spc',
  },
  {
    id: 'defects',
    name: '不良与异常管理',
    icon: 'WarningFilled',
    path: '/defects',
    closable: true,
    order: 5,
    module: 'defects',
  },
  {
    id: 'trace',
    name: '质量追溯',
    icon: 'Connection',
    path: '/trace',
    closable: true,
    order: 6,
    module: 'trace',
  },
  {
    id: 'complaints',
    name: '客诉与8D',
    icon: 'ChatLineSquare',
    path: '/complaints',
    closable: true,
    order: 7,
    module: 'complaints',
  },
  {
    id: 'ai',
    name: 'AI质量分析',
    icon: 'Monitor',
    path: '/ai',
    closable: true,
    order: 8,
    module: 'ai',
  },
  {
    id: 'equipment-link',
    name: '设备质量联动',
    icon: 'Setting',
    path: '/equipment-link',
    closable: true,
    order: 9,
    module: 'equipment-link',
  },
  {
    id: 'documents',
    name: '文件与体系',
    icon: 'Document',
    path: '/documents',
    closable: true,
    order: 10,
    module: 'documents',
  },
  {
    id: 'audits',
    name: '审核与稽核',
    icon: 'EditPen',
    path: '/audits',
    closable: true,
    order: 11,
    module: 'audits',
  },
  {
    id: 'reports',
    name: '报表中心',
    icon: 'DataBoard',
    path: '/reports',
    closable: true,
    order: 12,
    module: 'reports',
  },
  {
    id: 'settings',
    name: '系统管理',
    icon: 'Tools',
    path: '/settings',
    closable: true,
    order: 13,
    module: 'settings',
  },
]
