import type { MenuConfig } from '@/types/tab'

export const menuConfigs: MenuConfig[] = [
  {
    id: 'dashboard',
    name: '首页',
    icon: 'Odometer',
    path: '/dashboard',
    closable: false,
    order: 0,
    module: 'dashboard',
  },
  {
    id: 'iqc',
    name: 'IQC来料检验',
    icon: 'Goods',
    path: '/iqc',
    closable: true,
    order: 1,
    module: 'iqc',
  },
  {
    id: 'ipqc',
    name: 'IPQC过程检验',
    icon: 'Tools',
    path: '/ipqc',
    closable: true,
    order: 2,
    module: 'ipqc',
  },
  {
    id: 'fqc',
    name: 'FQC/OQC成品检验',
    icon: 'Finished',
    path: '/fqc',
    closable: true,
    order: 3,
    module: 'fqc',
  },
  {
    id: 'spc',
    name: 'SPC统计分析',
    icon: 'DataAnalysis',
    path: '/spc',
    closable: true,
    order: 4,
    module: 'spc',
  },
  {
    id: 'defects',
    name: '不良与异常管理',
    icon: 'WarningFilled',
    path: '/defects',
    closable: true,
    order: 5,
    module: 'defects',
  },
  {
    id: 'trace',
    name: '质量追溯',
    icon: 'Connection',
    path: '/trace',
    closable: true,
    order: 6,
    module: 'trace',
  },
  {
    id: 'complaints',
    name: '客诉与8D',
    icon: 'ChatLineSquare',
    path: '/complaints',
    closable: true,
    order: 7,
    module: 'complaints',
  },
  {
    id: 'ai',
    name: 'AI质量分析',
    icon: 'Monitor',
    path: '/ai',
    closable: true,
    order: 8,
    module: 'ai',
  },
  {
    id: 'equipment-link',
    name: '设备质量联动',
    icon: 'Setting',
    path: '/equipment-link',
    closable: true,
    order: 9,
    module: 'equipment-link',
  },
  {
    id: 'documents',
    name: '文件与体系',
    icon: 'Document',
    path: '/documents',
    closable: true,
    order: 10,
    module: 'documents',
  },
  {
    id: 'audits',
    name: '审核与稽核',
    icon: 'EditPen',
    path: '/audits',
    closable: true,
    order: 11,
    module: 'audits',
  },
  {
    id: 'reports',
    name: '报表中心',
    icon: 'DataBoard',
    path: '/reports',
    closable: true,
    order: 12,
    module: 'reports',
  },
  {
    id: 'settings',
    name: '系统管理',
    icon: 'Tools',
    path: '/settings',
    closable: true,
    order: 13,
    module: 'settings',
  },
]
